service: tuktuk-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev
  environment:
    NODE_ENV: ${param:NODE_ENV, "production"}
    MONGODB_URI: ${param:MONGODB_URI, ""}
    JWT_SECRET: ${param:JWT_SECRET, ""}
    JWT_EXPIRES_IN: ${param:JWT_EXPIRES_IN, "1d"}
    SWAGGER_SERVER_URL: ${param:SWAGGER_SERVER_URL, ""}

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}